
public enum ENotificationMsgType : uint
{
    ClientRequest,
    Login,
    Register,
    MatchingGame,
    ServerResponse,
    MacthingResponse,
    SyncPlayerResponse,
    SyncPostionResponse,
    CarRun,
    CarBrake,
    CarLight,
    CarControl,
    StartCount,
    CarControlFromServer,
    GameFinish,
    GameFinishResponse,
    GameFinishDisplay,
    ChatResponse,
    ChatFromServer,
    CoinResponse,
    CoinFromServer,
}